name: twilio_voice_sms
description: Twilio Programmable Voice (VoIP) and REST SMS for Flutter — Android + iOS.
version: 0.2.0
homepage: https://github.com/minhtri1401/flutter_twilio
repository: https://github.com/minhtri1401/flutter_twilio
issue_tracker: https://github.com/minhtri1401/flutter_twilio/issues
topics:
  - twilio
  - voice
  - voip
  - sms

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^22.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dev.flutter_twilio
        pluginClass: FlutterTwilioPlugin
      ios:
        pluginClass: FlutterTwilioPlugin
